namespace saisei {
    // ページ表示用パラメータ properties相当
    export var prefixPath: string = "images/";
    export var topPagePhoto: string = "201011sogetsuten_hagiya";
    export var newsRowNumber: number = 3;
    export var maxPhotoInPage: number = 5;
    export var sogetsuLink: string = "http://www.sogetsu.or.jp/study/class/areaB/8/0038738001.html";
    export var imgOrderKey: string = "hagiya";

    // データの追加場所（暫定）
    export var eventListData: SaiseiNews[] = [
        { yyyymmdd: 20170223, yyyyNen: "2017年", mmddaaStart: "2月23日（木）", mmddaaEnd: "2月28日（火）", eventName: "草月創流90周年記念", location: "水戸京成百貨店", titleName: "茨城県支部草月いけばな展" },
        { yyyymmdd: 20161126, yyyyNen: "2016年", mmddaaStart: "11月26日（土）", mmddaaEnd: "11月27日（日）", eventName: "日立地区文化祭", location: "日立市民会館", titleName: "" },
        { yyyymmdd: 20161026, yyyyNen: "2016年", mmddaaStart: "10月26日（水）", mmddaaEnd: "10月31日（月）", eventName: "第98回草月いけばな展", location: "日本橋高島屋8階ホール", titleName: "「花は、私になる。」" },
        { yyyymmdd: 20161028, yyyyNen: "2016年", mmddaaStart: "10月28日（金）", mmddaaEnd: "10月31日（月）", eventName: "第51回茨城県芸術祭", location: "県民文化センター", titleName: "平成28年度日立市芸術祭" },
        { yyyymmdd: 20160521, yyyyNen: "2016年", mmddaaStart: "5月21日（土）", mmddaaEnd: "5月22日（日）", eventName: "平成28年度日立市芸術祭", location: "日立市教育プラザ2階ギャラリー", titleName: "「初夏のいけばな展」" },
        { yyyymmdd: 20151127, yyyyNen: "2015年", mmddaaStart: "11月27日（金）", mmddaaEnd: "11月29日（日）", eventName: "日立地区文化祭", location: "日立市民会館", titleName: "" },
        { yyyymmdd: 20151029, yyyyNen: "2015年", mmddaaStart: "10月29日（木）", mmddaaEnd: "11月3日（火・祝）", eventName: "第97回草月いけばな展", location: "日本橋高島屋8階ホール", titleName: "「いけばなは繪だという、音楽でも、彫刻でもある」" },
        { yyyymmdd: 20151010, yyyyNen: "2015年", mmddaaStart: "10月10日（土）", mmddaaEnd: "10月13日（火）", eventName: "第50回茨城県芸術祭", location: "県民文化センター", titleName: "" },
        { yyyymmdd: 20151007, yyyyNen: "2015年", mmddaaStart: "10月7日（水）", mmddaaEnd: "10月14日（水）", eventName: "第42回日本いけばな芸術展", location: "日本橋高島屋8階ホール", titleName: "" },
        { yyyymmdd: 20141106, yyyyNen: "2014年", mmddaaStart: "11月6日（金）", mmddaaEnd: "11月8日（日）", eventName: "日立地区文化祭", location: "日立市民会館", titleName: "" },
        { yyyymmdd: 20141030, yyyyNen: "2014年", mmddaaStart: "10月30日（水）", mmddaaEnd: "11月3日（月）", eventName: "第49回茨城県芸術祭", location: "県民文化センター", titleName: "" },
        { yyyymmdd: 20141030, yyyyNen: "2014年", mmddaaStart: "10月30日（水）", mmddaaEnd: "11月3日（月）", eventName: "第96回草月いけばな展", location: "日本橋高島屋8階ホール", titleName: "「目に見えぬものをいけよ」" },
        { yyyymmdd: 20140828, yyyyNen: "2014年", mmddaaStart: "8月28日（水）", mmddaaEnd: "9月2日（火）", eventName: "草月会茨城県支部いけばな展", location: "水戸京成百貨店", titleName: "「初秋の空間を彩る」" },
        { yyyymmdd: 20140524, yyyyNen: "2014年", mmddaaStart: "5月24日（土）", mmddaaEnd: "5月25日（日）", eventName: "平成26年度日立市芸術祭", location: "日立市教育プラザ2階ギャラリー", titleName: "「初夏のいけばな展」" },
        { yyyymmdd: 20140515, yyyyNen: "2014年", mmddaaStart: "5月15日（木）", mmddaaEnd: "5月20日（火）", eventName: "日本いけばな芸術北関東展", location: "宇都宮  東武宇都宮百貨店  5階イベントプラザ", titleName: "" },
        { yyyymmdd: 20131206, yyyyNen: "2013年", mmddaaStart: "12月6日（金）", mmddaaEnd: "12月8日（日）", eventName: "日立地区文化祭", location: "日立市民会館", titleName: "" },
        { yyyymmdd: 20131030, yyyyNen: "2013年", mmddaaStart: "10月30日（水）", mmddaaEnd: "11月5日（火）", eventName: "第95回草月いけばな展", location: "日本橋高島屋8階ホール", titleName: "「花おどる」" },
        { yyyymmdd: 20130531, yyyyNen: "2013年", mmddaaStart: "5月31日（金）", mmddaaEnd: "6月2日（日）", eventName: "第45回水戸市芸術祭いけばな展", location: "水戸芸術館現代美術ギャラリー", titleName: "" },
        { yyyymmdd: 20130522, yyyyNen: "2013年", mmddaaStart: "5月22日（水）", mmddaaEnd: "5月27日（月）", eventName: "第46回日本いけばな芸術展", location: "日本橋高島屋8階ホール", titleName: "" },
        { yyyymmdd: 20130518, yyyyNen: "2013年", mmddaaStart: "5月18日（土）", mmddaaEnd: "5月19日（日）", eventName: "平成25年度日立市芸術祭", location: "日立市教育プラザ2階ギャラリー", titleName: "「初夏のいけばな展」" },
        { yyyymmdd: 20121101, yyyyNen: "2012年", mmddaaStart: "11月1日（水）", mmddaaEnd: "11月6日（火）", eventName: "第94回草月いけばな展", location: "日本橋高島屋8階ホール", titleName: "「花ときめき」" },
        { yyyymmdd: 20121102, yyyyNen: "2012年", mmddaaStart: "11月2日（金）", mmddaaEnd: "11月5日（月）", eventName: "第47回茨城県芸術祭", location: "県民文化センター", titleName: "" },
        { yyyymmdd: 20120518, yyyyNen: "2012年", mmddaaStart: "5月18日（金）", mmddaaEnd: "5月20日（日）", eventName: "第44回水戸市芸術祭いけばな展", location: "水戸芸術館現代美術ギャラリー", titleName: "" },
        { yyyymmdd: 20120505, yyyyNen: "2012年", mmddaaStart: "5月5日（土）", mmddaaEnd: "5月6日（日）", eventName: "平成24年度日立市芸術祭", location: "日立市教育プラザ2階ギャラリー", titleName: "「初夏のいけばな展」" },
        { yyyymmdd: 20111103, yyyyNen: "2011年", mmddaaStart: "11月3日（水）", mmddaaEnd: "11月8日（火）", eventName: "勅使河原茜家元継承10年記念 第93回草月いけばな展", location: "日本橋高島屋8階ホール", titleName: "「花のちからを信じて」" },
        { yyyymmdd: 20111103, yyyyNen: "2011年", mmddaaStart: "11月3日（水）", mmddaaEnd: "11月6日（日）", eventName: "第46回茨城県芸術祭", location: "県民文化センター", titleName: "" },
        { yyyymmdd: 20111012, yyyyNen: "2011年", mmddaaStart: "10月12日（水）", mmddaaEnd: "10月17日（月）", eventName: "第42回日本いけばな芸術展", location: "日本橋高島屋8階ホール", titleName: "" },
        { yyyymmdd: 20110217, yyyyNen: "2011年", mmddaaStart: "2月17日（木）", mmddaaEnd: "2月22日（火）", eventName: "勅使河原茜家元継承10年記念  草月会茨城県支部いけばな展「色の詩」", location: "水戸京成百貨店", titleName: "「色の詩」" },
        { yyyymmdd: 20101119, yyyyNen: "2010年", mmddaaStart: "11月19日（金）", mmddaaEnd: "11月21日（日）", eventName: "日立地区文化祭", location: "日立市民会館", titleName: "" },
        { yyyymmdd: 20101103, yyyyNen: "2010年", mmddaaStart: "11月3日（水）", mmddaaEnd: "11月8日（月）", eventName: "第92回草月いけばな展", location: "日本橋高島屋8階ホール", titleName: "「花遊ぶ」" },
        { yyyymmdd: 20101030, yyyyNen: "2010年", mmddaaStart: "10月30日（土）", mmddaaEnd: "11月3日（火）", eventName: "第45回茨城県芸術祭", location: "県民文化センター", titleName: "" },
        { yyyymmdd: 20100522, yyyyNen: "2010年", mmddaaStart: "5月22日（土）", mmddaaEnd: "5月23日（日）", eventName: "平成23年度日立市芸術祭", location: "日立市教育プラザ2階ギャラリー", titleName: "「初夏のいけばな展」" },
        { yyyymmdd: 20091105, yyyyNen: "2009年", mmddaaStart: "11月5日（木）", mmddaaEnd: "11月10日（火）", eventName: "第91回草月いけばな展", location: "日本橋高島屋8階ホール", titleName: "「花歌う」" },
        { yyyymmdd: 20091031, yyyyNen: "2009年", mmddaaStart: "10月31日（土）", mmddaaEnd: "11月5日（木）", eventName: "第43回茨城県芸術祭", location: "県民文化センター", titleName: "" },
        { yyyymmdd: 20091030, yyyyNen: "2009年", mmddaaStart: "10月30日（金）", mmddaaEnd: "11月1日（日）", eventName: "日立地区文化祭", location: "日立市民会館", titleName: "" },
        { yyyymmdd: 20090522, yyyyNen: "2009年", mmddaaStart: "5月22日（金）", mmddaaEnd: "5月24日（日）", eventName: "第42回水戸市芸術祭いけばな展", location: "水戸芸術館現代美術ギャラリー", titleName: "" },
        { yyyymmdd: 20090521, yyyyNen: "2009年", mmddaaStart: "5月21日（木）", mmddaaEnd: "5月24日（日）", eventName: "平成21年度日立市芸術祭", location: "日立市教育プラザ", titleName: "「初夏のいけばな展」" },
        { yyyymmdd: 20090401, yyyyNen: "2009年", mmddaaStart: "4月1日（水）", mmddaaEnd: "4月6日（月）", eventName: "第41回日本いけばな芸術展", location: "日本橋高島屋8階ホール", titleName: "" },
        { yyyymmdd: 20090326, yyyyNen: "2009年", mmddaaStart: "3月26日（木）", mmddaaEnd: "3月28日（土）", eventName: "伝えていこう草月の技と心最終章卒業展", location: "東京草月会館1Ｆプラザ", titleName: "「私の器に私の花」" },
        { yyyymmdd: 20081114, yyyyNen: "2008年", mmddaaStart: "11月14日（金）", mmddaaEnd: "11月16日（日）", eventName: "日立地区文化祭", location: "日立市民会館", titleName: "" },
        { yyyymmdd: 20081106, yyyyNen: "2008年", mmddaaStart: "11月6日（木）", mmddaaEnd: "11月11日（火）", eventName: "第90回草月いけばな展", location: "日本橋高島屋8階ホール", titleName: "「花笑み」" },
        { yyyymmdd: 20081103, yyyyNen: "2008年", mmddaaStart: "11月3日（月）", mmddaaEnd: "11月8日（土）", eventName: "第23回国民文化祭・いばらき2008", location: "茨城県県民文化センター", titleName: "偕楽の風花悠々  華道フェスティバル" },
        { yyyymmdd: 20081016, yyyyNen: "2008年", mmddaaStart: "10月16日（木）", mmddaaEnd: "10月18日（土）", eventName: "日立市役所文化祭", location: "日立市役所内", titleName: "" },
        { yyyymmdd: 20081001, yyyyNen: "2008年", mmddaaStart: "10月1日（水）", mmddaaEnd: "10月6日（月）", eventName: "草月いけばな展", location: "柏高島屋", titleName: "「しあわせの花」" },
        { yyyymmdd: 20080523, yyyyNen: "2008年", mmddaaStart: "5月23日（金）", mmddaaEnd: "5月25日（日）", eventName: "第41回水戸市芸術祭いけばな展", location: "水戸芸術館現代美術ギャラリー", titleName: "" },
        { yyyymmdd: 20080522, yyyyNen: "2008年", mmddaaStart: "5月22日（木）", mmddaaEnd: "5月25日（日）", eventName: "日立市芸術祭", location: "日立市教育プラザ", titleName: "「初夏のいけばな展」" },
        { yyyymmdd: 20170105, yyyyNen: "2017年", mmddaaStart: "1月5日（木）", mmddaaEnd: "1月16日（月）", eventName: "迎え花", location: "日立シビックセンター", titleName: "「迎春」" },
        { yyyymmdd: 20150101, yyyyNen: "2015年", mmddaaStart: "1月", mmddaaEnd: "", eventName: "迎え花", location: "日立シビックセンター", titleName: "「新春落語会」" },
        { yyyymmdd: 20150101, yyyyNen: "2015年", mmddaaStart: "1月", mmddaaEnd: "", eventName: "迎え花", location: "日立シビックセンター", titleName: "「お正月」" },
        { yyyymmdd: 20120121, yyyyNen: "2012年", mmddaaStart: "1月21日", mmddaaEnd: "", eventName: "迎え花", location: "日立シビックセンター", titleName: "「新春落語会」" },
        { yyyymmdd: 20120107, yyyyNen: "2012年", mmddaaStart: "1月7日", mmddaaEnd: "1月15日", eventName: "迎え花", location: "日立シビックセンター", titleName: "「お正月」" },
        { yyyymmdd: 20080320, yyyyNen: "2008年", mmddaaStart: "3月20日", mmddaaEnd: "5月6日", eventName: "竹の造形", location: "日立市郷土博物館", titleName: "" },
        { yyyymmdd: 20061006, yyyyNen: "2006年", mmddaaStart: "10月6日", mmddaaEnd: "10月8日", eventName: "今宵の月と花と謡講", location: "日立市郷土博物館", titleName: "" },
        { yyyymmdd: 20990101, yyyyNen: "2099年", mmddaaStart: "1月1日", mmddaaEnd: "12月31日", eventName: "イベント名 テンプレート", location: "開催場所 テンプレート", titleName: "「副題 テンプレート」" }
    ];

    export var imgPathList: string[] = [
        "201003okeiko_horikoshi.jpg",
        "201003okeiko_kawai.jpg",
        "201003okeiko_kikuchi.jpg",
        "201003okeiko_kouji.jpg",
        "201003okeiko_namekawa.jpg",
        "201003okeiko_nohara.jpg",
        "201003okeiko_omori.jpg",
        "201003okeiko_other.jpg",
        "201003okeiko_suzuki.jpg",
        "201003okeiko_takamaru.jpg",
        "201003okeiko_tomita.jpg",
        "201003okeiko_yabuki.jpg",
        "201011sogetsuten_hagiya.jpg",
        "201011sogetsuten_kouji.jpg",
        "201011sogetsuten_omori.jpg",
        "201011sogetsuten_takamaru.jpg",
        "201201hatsuike_hagiya.jpg",
        "201201hatsuike_horikoshi.jpg",
        "201201hatsuike_kawai.jpg",
        "201201hatsuike_kikuchi.jpg",
        "201201hatsuike_kouji.jpg",
        "201201hatsuike_namekawa.jpg",
        "201201hatsuike_omori.jpg",
        "201201hatsuike_suzuki.jpg",
        "201201hatsuike_takamaru.jpg",
        "201201hatsuike_tomita.jpg",
        "201410sogetsuten_hagiya.jpg",
        "201410sogetsuten_kouji.jpg",
        "201410sogetsuten_omori.jpg",
        "201411hitachi_hagiya.jpg",
        "201411hitachi_kikuchi.jpg",
        "201411hitachi_namekawa.jpg",
        "201411hitachi_omori.jpg",
        "201411hitachi_suzuki.jpg",
        "201411kenten_gassaku.jpg",
        "201411sogetsuten_hagiya.jpg",
        "201411sogetsuten_kouji.jpg",
        "201411sogetsuten_omori.jpg",
        "201501civic_gassaku.jpg",
        "201511kenten_gassaku.jpg",
        "201511kenten_omori.jpg",
        "201605hitachi_hagiya.jpg",
        "201605hitachi_kikuchi.jpg",
        "201605hitachi_namekawa.jpg",
        "201605hitachi_omori.jpg",
        "201605hitachi_other.jpg",
        "201605hitachi_suzuki.jpg",
        "201610kenten_gassaku.jpg",
        "201610kenten_other.jpg",
        "201610sogetsuten_hagiya.jpg",
        "201610sogetsuten_kouji.jpg",
        "201610sogetsuten_omori.jpg",
        "201610sogetsuten_tomita.jpg",
        "201702shibuten_gassaku.jpg",
        "201702shibuten_kawai.jpg",
        "201702shibuten_kitami.jpg",
        "201702shibuten_kouji.jpg",
        "201702shibuten_suzuki.jpg",
        "201702shibuten_takamaru.jpg",
        "201702shibuten_tomita.jpg"
    ];

    export var rulePhotoName: SaiseiPhotoName[] = [
        { shortName: "_hagiya", eventHint: "", locationHint: "", creatorHint: "萩谷灑清" },
        { shortName: "_tomita", eventHint: "", locationHint: "", creatorHint: "富田灑智" },
        { shortName: "_namekawa", eventHint: "", locationHint: "", creatorHint: "滑川灑泰" },
        { shortName: "_kikuchi", eventHint: "", locationHint: "", creatorHint: "菊池灑幸" },
        { shortName: "_takamaru", eventHint: "", locationHint: "", creatorHint: "高丸清光" },
        { shortName: "_shida", eventHint: "", locationHint: "", creatorHint: "志田清珠" },
        { shortName: "_omori", eventHint: "", locationHint: "", creatorHint: "大森灑泉" },
        { shortName: "_suzuki", eventHint: "", locationHint: "", creatorHint: "鈴木灑恵" },
        { shortName: "_kawai", eventHint: "", locationHint: "", creatorHint: "河合灑楓" },
        { shortName: "_horikoshi", eventHint: "", locationHint: "", creatorHint: "堀越灑観" },
        { shortName: "_kouji", eventHint: "", locationHint: "", creatorHint: "孝治蓮唱" },
        { shortName: "_gassaku", eventHint: "", locationHint: "", creatorHint: "合作" },
        { shortName: "_other", eventHint: "", locationHint: "", creatorHint: "その他" },
        { shortName: "_kitami", eventHint: "", locationHint: "", creatorHint: "北見陽子" },
        { shortName: "_iwasaki", eventHint: "", locationHint: "", creatorHint: "岩﨑灑加" },
        { shortName: "_yabuki", eventHint: "", locationHint: "", creatorHint: "矢吹" },
        { shortName: "_nohara", eventHint: "", locationHint: "", creatorHint: "野原" },
        { shortName: "_ogasawara", eventHint: "", locationHint: "", creatorHint: "小笠原" },
        { shortName: "_tiba", eventHint: "", locationHint: "", creatorHint: "千葉" },
        { shortName: "_gotou", eventHint: "", locationHint: "", creatorHint: "後藤" },
        { shortName: "_nishizawa", eventHint: "", locationHint: "", creatorHint: "西沢" },
        { shortName: "_katue", eventHint: "", locationHint: "", creatorHint: "鈴木(克江) " },
        { shortName: "_sekine", eventHint: "", locationHint: "", creatorHint: "関根" },
        { shortName: "_kayane", eventHint: "", locationHint: "", creatorHint: "茅根" },
        { shortName: "_kasuya", eventHint: "", locationHint: "", creatorHint: "粕谷" },
        { shortName: "_usami", eventHint: "", locationHint: "", creatorHint: "宇佐美" },
        { shortName: "_doumeki", eventHint: "", locationHint: "", creatorHint: "百目鬼" },
        { shortName: "_miki", eventHint: "", locationHint: "", creatorHint: "菊池(美紀) " },
        { shortName: "_ikeda", eventHint: "", locationHint: "", creatorHint: "池田" },
        { shortName: "_endou", eventHint: "", locationHint: "", creatorHint: "遠藤" },
        { shortName: "_senba", eventHint: "", locationHint: "", creatorHint: "仙波" },
        { shortName: "_inoue", eventHint: "", locationHint: "", creatorHint: "井上" },
        { shortName: "_yamamoto", eventHint: "", locationHint: "", creatorHint: "山本" },
        { shortName: "_kawarazaki", eventHint: "", locationHint: "", creatorHint: "河原崎" },
        { shortName: "sogetsuten", eventHint: "草月", locationHint: "", creatorHint: "" },
        { shortName: "hitachi", eventHint: "日立", locationHint: "日立", creatorHint: "" },
        { shortName: "kenten", eventHint: "茨城県芸術祭", locationHint: "", creatorHint: "" },
        { shortName: "civic", eventHint: "", locationHint: "シビックセンター", creatorHint: "" },
        { shortName: "shibuten", eventHint: "茨城県支部", locationHint: "", creatorHint: "" },
        { shortName: "okeiko", eventHint: "", locationHint: "教室", creatorHint: "" },
        { shortName: "hatsuike", eventHint: "迎春", locationHint: "教室", creatorHint: "" },
        { shortName: "culture", eventHint: "", locationHint: "カルチャー", creatorHint: "" },
        { shortName: "flowerwork", eventHint: "フラワーク", locationHint: "", creatorHint: "" },
        { shortName: "meigetsu", eventHint: "名月", locationHint: "", creatorHint: "" },
        { shortName: "kyodo", eventHint: "", locationHint: "郷土", creatorHint: "" },
        { shortName: "rakugo", eventHint: "落語", locationHint: "", creatorHint: "" },
        { shortName: "xmas", eventHint: "クリスマス", locationHint: "", creatorHint: "" },
        { shortName: "syogatsu", eventHint: "正月", locationHint: "", creatorHint: "" },
        { shortName: "tanabata", eventHint: "七夕", locationHint: "カルチャー", creatorHint: "" },
        { shortName: "geijyutsukan", eventHint: "水戸市芸術祭", locationHint: "芸術館", creatorHint: "" },
        { shortName: "kashiwa", eventHint: "", locationHint: "柏", creatorHint: "" },
        { shortName: "shiyakusyo", eventHint: "", locationHint: "市役所", creatorHint: "" },
        { shortName: "kokubun", eventHint: "国民文化祭", locationHint: "", creatorHint: "" },
        { shortName: "wazatokokoro", eventHint: "技と心", locationHint: "", creatorHint: "" },
        { shortName: "ikegei", eventHint: "いけばな芸術", locationHint: "", creatorHint: "" }
    ];
}